### ISSUE TITLE
Error encountered when running build.sh for MacOS

### ISSUE THREAD

**Issue by mrpau-eugene** [learningequality/ka-lite-installers#466]
## Summary

I was following the documentation for building the MacOS Installers but I encountered a problem after running `build.sh`

## Version

 - Installer: OSX
 - Version: 0.17.x

## Traceback or server.log snippet

```
Building wheels for collected packages: ka-lite
  Running setup.py bdist_wheel for ka-lite ... error
  Complete output from command /Users/yujin/Desktop/ka-lite-installers/osx/temp/ka-lite/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/66/wl70mm057b3bh1xz05r48vyh0000gq/T/pip-2L8zYh-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/66/wl70mm057b3bh1xz05r48vyh0000gq/T/tmpjRUZOcpip-wheel- --python-tag cp27:
  Already blocking...
  Already blocking...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/66/wl70mm057b3bh1xz05r48vyh0000gq/T/pip-2L8zYh-build/setup.py", line 52, in <module>
      "Harmless: We don't support auto-converting to .whl format. Please "
  RuntimeError: Harmless: We don't support auto-converting to .whl format. Please fetch the .whl instead of the tarball.

  ----------------------------------------
  Failed building wheel for ka-lite
  Running setup.py clean for ka-lite
Failed to build ka-lite
Installing collected packages: ka-lite
  Running setup.py install for ka-lite ... done
Successfully installed ka-lite-0.18.0.dev0
.. Running pip install wheel...
Requirement already satisfied: wheel in ./venv/lib/python2.7/site-packages
11/16. Running 'make dist'...
.. Running make dist...
rm -fr build/
rm -fr dist/
rm -rf .kalite_dist_tmp
rm -fr .eggs/
rm -fr .pip-temp/
rm -fr kalite/database/templates
rm -fr kalite/static-libraries/docs
find kalite/packages/dist/* -maxdepth 0 -type d -exec rm -fr {} +
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
rm -fr .tox/
rm -f .coverage
rm -fr htmlcov/
npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yujin/.npm/_logs/2017-08-22T05_45_46_529Z-debug.log
make: *** [clean-assets] Error 1
.. Abort!  Error/s encountered running 'make dist'.
```

## Errors inside .npm/_logs/
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'cache', 'clean' ]
2 info using npm@5.3.0
3 info using node@v6.10.3
4 verbose npm-session a8a4321ad8e41395
5 verbose stack Error: As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
5 verbose stack
5 verbose stack If you're sure you want to delete the entire cache, rerun this command with --force.
5 verbose stack     at clean (/usr/local/lib/node_modules/npm/lib/cache.js:70:22)
5 verbose stack     at EventEmitter.cache (/usr/local/lib/node_modules/npm/lib/cache.js:45:16)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:150:13)
5 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:84:30)
5 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
6 verbose cwd /Users/yujin/Desktop/ka-lite-installers/osx/temp/ka-lite
7 verbose Darwin 16.7.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "cache" "clean"
9 verbose node v6.10.3
10 verbose npm  v5.3.0
11 error As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
11 error
11 error If you're sure you want to delete the entire cache, rerun this command with --force.
12 verbose exit [ 1, true ]

```
## How to reproduce

1. Follow the **Getting Started** guide [here](https://github.com/learningequality/ka-lite-installers/tree/master/osx#getting-started).

**Comment by mrpau-eugene** [comment]
Seems that using `npm` version 5 causes this error. Downloaded version 3 instead. Closing this now.
